import { adminContextError, getAdminContext } from "../../../../../../lib/adminAuth";
export const dynamic="force-dynamic";
function redact(value){let text=typeof value==="string"?value:JSON.stringify(value??null,null,2);return text.replace(/(authorization|api[_-]?key|access[_-]?token|refresh[_-]?token|service[_-]?role|cookie|secret)(["'\s:=]+)([^\s,"'}]+)/gi,"$1$2[REDACTED]").replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [REDACTED]").slice(0,120000);}
export async function GET(request,{params}){const context=await getAdminContext(request);if(context.error)return adminContextError(context);try{const {id}=await params;const url=new URL(request.url);const ruleId=url.searchParams.get("ruleId");const {data:batch,error:bErr}=await context.admin.from("admin_test_batches").select("id,title,created_at,settings").eq("id",id).eq("created_by",context.user.id).maybeSingle();if(bErr)throw bErr;if(!batch)return new Response("Masstestet hittades inte.",{status:404});let rulesQuery=context.admin.from("automation_rules").select("id,brand_profile_id,name,platform,content_type_id,content_type_label,content_format,queue_source,admin_test_job_key,created_at,updated_at,last_error").eq("admin_test_batch_id",id);if(ruleId)rulesQuery=rulesQuery.eq("id",ruleId);const {data:rules,error:rErr}=await rulesQuery;if(rErr)throw rErr;const ruleIds=(rules||[]).map((r)=>r.id);const brandIds=[...new Set((rules||[]).map((r)=>r.brand_profile_id).filter(Boolean))];const [occ,logs,inc,brands]=await Promise.all([
ruleIds.length?context.admin.from("automation_occurrences").select("*").in("automation_rule_id",ruleIds).order("started_at",{ascending:true}):Promise.resolve({data:[]}),
ruleIds.length?context.admin.from("automation_run_logs").select("*").in("rule_id",ruleIds).order("started_at",{ascending:true}):Promise.resolve({data:[]}),
ruleIds.length?context.admin.from("admin_runtime_incidents").select("*").in("rule_id",ruleIds).order("created_at",{ascending:true}):Promise.resolve({data:[]}),
brandIds.length?context.admin.from("brand_profiles").select("id,business_name,website_url").in("id",brandIds):Promise.resolve({data:[]})]);
const brandMap=Object.fromEntries((brands.data||[]).map((b)=>[b.id,b]));const failedRuleIds=new Set([...(occ.data||[]).filter((x)=>String(x.status||"")==="failed_terminal").map((x)=>x.automation_rule_id),...(logs.data||[]).filter((x)=>String(x.status||"")==="failed").map((x)=>x.rule_id),(rules||[]).filter((x)=>x.last_error).map((x)=>x.id)].flat().filter(Boolean));const diagnosticRules=ruleId?(rules||[]):(rules||[]).filter((r)=>failedRuleIds.has(r.id));const header=["SPREELO ADMIN MASS TEST DIAGNOSTIC",`Batch: ${batch.title||batch.id}`,`Batch ID: ${batch.id}`,`Exported: ${new Date().toISOString()}`,`Vercel env: ${process.env.VERCEL_ENV||"unknown"}`,`Vercel deployment: ${process.env.VERCEL_DEPLOYMENT_ID||process.env.VERCEL_GIT_COMMIT_SHA||"unknown"}`,"Secrets/tokens are redacted automatically.",""];const sections=diagnosticRules.map((rule)=>{const o=(occ.data||[]).filter((x)=>x.automation_rule_id===rule.id);const l=(logs.data||[]).filter((x)=>x.rule_id===rule.id);const incidents=(inc.data||[]).filter((x)=>x.rule_id===rule.id||x.admin_test_job_key===rule.admin_test_job_key);return ["=".repeat(72),`JOB ${rule.admin_test_job_key||rule.id}`,`Rule ID: ${rule.id}`,`Brand: ${brandMap[rule.brand_profile_id]?.business_name||rule.brand_profile_id}`,`Website: ${brandMap[rule.brand_profile_id]?.website_url||"—"}`,`Campaign/plan: ${rule.name||"—"}`,`Format: ${rule.content_type_label||rule.content_type_id||"—"} (${rule.content_format||"—"})`,`Platform: ${rule.platform||"—"}`,`Rule last error: ${rule.last_error||"—"}`,"\nOCCURRENCES\n"+redact(o),"\nRUN LOGS\n"+redact(l),"\nINCIDENTS\n"+redact(incidents)].join("\n");});const text=[...header,...sections].join("\n");return new Response(text,{status:200,headers:{"Content-Type":"text/plain; charset=utf-8","Content-Disposition":`attachment; filename="spreelo-test-${id}${ruleId?`-${ruleId}`:"-errors"}.txt"`}});}catch(error){return new Response(`Could not build diagnostic: ${redact(error?.message||String(error))}`,{status:500,headers:{"Content-Type":"text/plain; charset=utf-8"}});}}
