const PROVIDERS = [
  {
    id: "cloudflare",
    label: "Cloudflare",
    headerTests: [
      ["server", /cloudflare/i],
      ["cf-ray", /.+/i],
      ["cf-mitigated", /challenge/i],
    ],
    bodyTests: [
      /cloudflare/i,
      /cf-error-code/i,
      /attention required!?\s*\|\s*cloudflare/i,
      /checking your browser before accessing/i,
      /enable javascript and cookies to continue/i,
    ],
  },
  {
    id: "aws_waf",
    label: "AWS WAF",
    headerTests: [
      ["x-amzn-requestid", /.+/i],
      ["x-amz-cf-id", /.+/i],
      ["server", /cloudfront/i],
    ],
    bodyTests: [/aws waf/i, /request blocked/i, /generated by cloudfront/i],
  },
  {
    id: "akamai",
    label: "Akamai",
    headerTests: [
      ["server", /akamai/i],
      ["x-akamai-transformed", /.+/i],
      ["akamai-grn", /.+/i],
    ],
    bodyTests: [/akamai/i, /reference #\d+\.[a-f0-9]+/i],
  },
  {
    id: "imperva",
    label: "Imperva",
    headerTests: [["x-iinfo", /.+/i]],
    bodyTests: [/imperva/i, /incapsula/i, /incident id/i],
  },
  {
    id: "sucuri",
    label: "Sucuri",
    headerTests: [
      ["server", /sucuri/i],
      ["x-sucuri-id", /.+/i],
      ["x-sucuri-cache", /.+/i],
    ],
    bodyTests: [/sucuri website firewall/i, /access denied - sucuri/i],
  },
  {
    id: "wordfence",
    label: "Wordfence",
    headerTests: [],
    bodyTests: [/wordfence/i, /generated by wordfence/i, /your access to this site has been limited/i],
  },
  {
    id: "fastly",
    label: "Fastly",
    headerTests: [
      ["via", /varnish/i],
      ["x-served-by", /cache-/i],
      ["x-cache", /(?:hit|miss|error)/i],
    ],
    bodyTests: [/fastly error/i, /fastly service unavailable/i],
  },
];

function readHeader(headers, name) {
  try {
    return String(headers?.get?.(name) || "");
  } catch {
    return "";
  }
}

const BLOCK_PAGE_TESTS = [
  /attention required!?\s*\|\s*cloudflare/i,
  /checking your browser before accessing/i,
  /enable javascript and cookies to continue/i,
  /cf-chl-/i,
  /challenge-platform/i,
  /request blocked/i,
  /access denied - sucuri/i,
  /your access to this site has been limited/i,
];

export function detectWebsiteSecurityProvider({ status = 0, headers, body = "" } = {}) {
  const source = String(body || "").slice(0, 20000);
  let best = null;

  for (const provider of PROVIDERS) {
    let score = 0;
    const evidence = [];

    for (const [headerName, pattern] of provider.headerTests) {
      const value = readHeader(headers, headerName);
      if (value && pattern.test(value)) {
        score += headerName === "server" ? 3 : 4;
        evidence.push(`${headerName}: ${value.slice(0, 160)}`);
      }
    }

    for (const pattern of provider.bodyTests) {
      if (pattern.test(source)) {
        score += 3;
        evidence.push(`body:${pattern.source}`);
      }
    }

    if (!best || score > best.score) {
      best = { ...provider, score, evidence };
    }
  }

  // Some security products deliberately return HTTP 200 for their challenge
  // page. Normal CDN headers alone are not sufficient evidence of a block.
  const hasBlockPageSignature = BLOCK_PAGE_TESTS.some((pattern) =>
    pattern.test(source)
  );
  const blocked =
    Number(status) === 403 ||
    Number(status) === 401 ||
    Number(status) === 429 ||
    hasBlockPageSignature;
  const highConfidence = Boolean(best && best.score >= 4);

  return {
    blocked,
    status: Number(status) || null,
    provider: highConfidence ? best.id : "unknown",
    providerLabel: highConfidence ? best.label : "Unknown security service",
    confidence: highConfidence ? (best.score >= 7 ? "high" : "medium") : "low",
    evidence: highConfidence ? best.evidence.slice(0, 6) : [],
  };
}

export class WebsiteSecurityBlockedError extends Error {
  constructor({ status = 403, provider = "unknown", providerLabel = "Unknown security service", confidence = "low", evidence = [], url = "" } = {}) {
    const providerText = provider === "unknown" ? "Website security protection" : providerLabel;
    super(`${providerText} blocked the website request (${status}).`);
    this.name = "WebsiteSecurityBlockedError";
    this.code = "WEBSITE_SECURITY_BLOCKED";
    this.status = Number(status) || 403;
    this.provider = provider;
    this.providerLabel = providerLabel;
    this.confidence = confidence;
    this.evidence = evidence;
    this.url = url;
  }
}

export function createWebsiteSecurityBlockedError({ response, body = "", url = "" } = {}) {
  const detection = detectWebsiteSecurityProvider({
    status: response?.status,
    headers: response?.headers,
    body,
  });

  return new WebsiteSecurityBlockedError({
    ...detection,
    url,
  });
}

export function getWebsiteSecurityCustomerMessage(error) {
  if (error?.code !== "WEBSITE_SECURITY_BLOCKED") return "";

  if (error.provider && error.provider !== "unknown") {
    return `${error.providerLabel} stopped the analysis. The website's security settings are blocking Spreelo's analysis connection. Your website administrator needs to allow Spreelo before the analysis can be completed.`;
  }

  return "The website's security protection stopped the analysis. Your website administrator needs to allow Spreelo's analysis connection before the analysis can be completed.";
}
