"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronRight, ClipboardCopy, FlaskConical, LoaderCircle, Play, RefreshCw, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import AppLayout from "../../../components/AppLayout";
import { supabase } from "../../../lib/supabaseClient";

async function headers(){const {data:{session}}=await supabase.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"}:{"Content-Type":"application/json"};}
const fmtMoney=(n)=>Number.isFinite(Number(n))?`${Number(n).toFixed(2).replace(".",",")} kr`:"—";
const fmtDate=(v)=>v?new Intl.DateTimeFormat("sv-SE",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
const statusLabel={queued:"Väntar",running:"Körs",completed:"Klar",completed_with_failures:"Klar med fel",failed:"Fel",waiting:"Väntar"};

export default function AdminMassTestsPage(){
  const [setup,setSetup]=useState({brands:[],formats:[],test_platforms:[],batches:[]});
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const [selected,setSelected]=useState({}); const [expanded,setExpanded]=useState({}); const [starting,setStarting]=useState(false);
  const [activeBatchId,setActiveBatchId]=useState(""); const [batchDetail,setBatchDetail]=useState(null); const [copying,setCopying]=useState("");

  async function loadSetup(){setLoading(true);setError("");try{const r=await fetch("/api/admin/mass-tests",{headers:await headers(),cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Kunde inte läsa masstest.");setSetup(d);setSelected((cur)=>{const next={...cur};for(const b of d.brands||[])if(!next[b.id]){const connected=(b.connected_platforms||[]).slice(0,2);const fallback=(d.test_platforms||[]).map((p)=>p.value).filter((p)=>p==="facebook"||p==="instagram").slice(0,2);next[b.id]={enabled:false,platforms:connected.length?connected:(fallback.length?fallback:["facebook"]),studio:{types:[],repeats:1,special:{}},campaigns:{}};}return next;});}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{loadSetup();},[]);
  async function loadBatch(id,silent=false){if(!id)return;try{const r=await fetch(`/api/admin/mass-tests/${id}`,{headers:await headers(),cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Kunde inte läsa testresultatet.");setBatchDetail(d);if(!["completed","completed_with_failures"].includes(d.batch?.status))setTimeout(()=>loadBatch(id,true),5000);}catch(e){if(!silent)setError(e.message);}}
  useEffect(()=>{if(activeBatchId)loadBatch(activeBatchId);},[activeBatchId]);

  const selectedBrands=useMemo(()=>setup.brands.filter((b)=>selected[b.id]?.enabled),[setup.brands,selected]);
  const summary=useMemo(()=>{let studio=0,campaign=0,estimated=0;const fm=Object.fromEntries(setup.formats.map((f)=>[f.id,f]));for(const b of selectedBrands){const s=selected[b.id];const reps=Math.max(1,Number(s?.studio?.repeats||1));studio+=(s?.studio?.types?.length||0)*reps;for(const id of s?.studio?.types||[])estimated+=Number(fm[id]?.estimatedCostSek||0)*reps;for(const c of b.campaigns||[]){const pick=s?.campaigns?.[c.id];if(!pick?.enabled)continue;const idx=Array.isArray(pick.postIndexes)&&pick.postIndexes.length?pick.postIndexes:c.post_plan.map((_,i)=>i);campaign+=idx.length;for(const i of idx)estimated+=Number(fm[c.post_plan?.[i]?.content_type_id]?.estimatedCostSek||0);}}return {studio,campaign,total:studio+campaign,estimated};},[selectedBrands,selected,setup.formats]);

  const updateBrand=(id,fn)=>setSelected((cur)=>({...cur,[id]:fn(cur[id]||{})}));
  const toggleFormat=(brandId,typeId)=>updateBrand(brandId,(s)=>({...s,studio:{...(s.studio||{}),types:(s.studio?.types||[]).includes(typeId)?(s.studio.types||[]).filter((x)=>x!==typeId):[...(s.studio?.types||[]),typeId]}}));
  const toggleCampaign=(brandId,campaign)=>updateBrand(brandId,(s)=>({...s,campaigns:{...(s.campaigns||{}),[campaign.id]:{enabled:!s.campaigns?.[campaign.id]?.enabled,postIndexes:s.campaigns?.[campaign.id]?.postIndexes||campaign.post_plan.map((_,i)=>i)}}}));
  const toggleCampaignPost=(brandId,campaignId,index)=>updateBrand(brandId,(s)=>{const old=s.campaigns?.[campaignId]||{enabled:true,postIndexes:[]};const has=old.postIndexes.includes(index);return {...s,campaigns:{...(s.campaigns||{}),[campaignId]:{...old,enabled:true,postIndexes:has?old.postIndexes.filter((i)=>i!==index):[...old.postIndexes,index].sort((a,b)=>a-b)}}};});

  async function startTest(){if(!summary.total)return setError("Välj minst en innehållstyp eller ett kampanjinlägg.");setStarting(true);setError("");setMessage("");try{const brands=selectedBrands.map((b)=>{const s=selected[b.id];return {brandProfileId:b.id,platforms:s.platforms,studio:{contentTypeIds:s.studio.types,repeats:Number(s.studio.repeats||1),special:s.studio.special||{}},campaigns:(b.campaigns||[]).filter((c)=>s.campaigns?.[c.id]?.enabled).map((c)=>({campaignId:c.id,postIndexes:s.campaigns[c.id].postIndexes}))};});const r=await fetch("/api/admin/mass-tests",{method:"POST",headers:await headers(),body:JSON.stringify({brands})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Masstestet kunde inte startas.");setMessage(`${d.batch.totalJobs} testjobb ligger nu i den vanliga kön och körs så snart workers blir lediga. Kundkrediter dras inte.`);setActiveBatchId(d.batch.id);await loadSetup();}catch(e){setError(e.message);}finally{setStarting(false);}}
  async function rerunFailed(){if(!activeBatchId)return;try{const r=await fetch(`/api/admin/mass-tests/${activeBatchId}`,{method:"POST",headers:await headers(),body:JSON.stringify({action:"rerun_failed"})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error);setMessage(`${d.rerunCount} misslyckade jobb har lagts tillbaka i kön.`);loadBatch(activeBatchId);}catch(e){setError(e.message);}}
  async function copyDiagnostic(ruleId){setCopying(ruleId);try{const r=await fetch(`/api/admin/mass-tests/${activeBatchId}/diagnostics?ruleId=${encodeURIComponent(ruleId)}`,{headers:await headers()});const text=await r.text();if(!r.ok)throw new Error(text);await navigator.clipboard.writeText(text);setMessage("Felsökningsloggen är kopierad och kan klistras in direkt i ChatGPT.");}catch(e){setError(e.message);}finally{setCopying("");}}
  async function downloadErrors(){const r=await fetch(`/api/admin/mass-tests/${activeBatchId}/diagnostics`,{headers:await headers()});const blob=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`spreelo-test-${activeBatchId}-diagnostics.txt`;a.click();URL.revokeObjectURL(a.href);}

  return <AppLayout>
    <main className="sp102-mass-page">
      <header className="sp102-hero"><div><span className="sp102-kicker"><FlaskConical size={16}/> ADMIN · MASSTEST</span><h1>Testa många varumärken på riktigt</h1><p>Välj varumärken, vanliga AI-inlägg och kalenderkampanjer. Jobben går genom samma produktionsflöde och samma worker-kö som vanligt, men kundkrediter dras inte.</p></div><div className="sp102-hero-proof"><ShieldCheck size={22}/><strong>Riktigt flöde</strong><span>Samma produktsökning, AI, media, kostnadsspårning och Godkänn.</span></div></header>
      {error?<div className="sp102-alert error"><AlertTriangle size={18}/>{error}</div>:null}{message?<div className="sp102-alert ok"><CheckCircle2 size={18}/>{message}</div>:null}
      {loading?<div className="sp102-loading"><LoaderCircle className="admin-spin"/>Laddar varumärken och kampanjer…</div>:<>
        <section className="sp102-builder"><div className="sp102-section-head"><div><span>1</span><div><h2>Välj varumärken</h2><p>Endast varumärken som ligger på ditt adminkonto visas här.</p></div></div><button onClick={loadSetup}><RefreshCw size={15}/> Uppdatera</button></div>
          <div className="sp102-brand-list">{setup.brands.map((brand)=>{const s=selected[brand.id]||{};const open=expanded[brand.id]||s.enabled;return <article key={brand.id} className={`sp102-brand ${s.enabled?"selected":""}`}>
            <div className="sp102-brand-top"><label><input type="checkbox" checked={!!s.enabled} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,enabled:e.target.checked}))}/><span><strong>{brand.business_name||"Namnlöst varumärke"}</strong><small>{brand.website_url||"Ingen webbplats"}</small></span></label><div className="sp102-brand-meta"><b>{brand.connected_platforms?.length||0} anslutna</b><b>{brand.campaigns?.length||0} kampanjer</b><button onClick={()=>setExpanded((v)=>({...v,[brand.id]:!open}))}>{open?<ChevronDown/>:<ChevronRight/>}</button></div></div>
            {s.enabled&&open?<div className="sp102-brand-body">
              <div className="sp102-sub"><h3>Testplattformar</h3><p className="sp102-muted">Välj vilka kanaler innehållet ska optimeras för. Anslutning krävs inte för masstest eftersom testinläggen inte publiceras automatiskt.</p><div className="sp102-chips">{(setup.test_platforms||[]).map((p)=>{const connected=(brand.connected_platforms||[]).includes(p.value);return <label key={p.value} className={s.platforms?.includes(p.value)?"active":""}><input type="checkbox" checked={s.platforms?.includes(p.value)||false} onChange={()=>updateBrand(brand.id,(v)=>({...v,platforms:v.platforms?.includes(p.value)?v.platforms.filter((x)=>x!==p.value):[...(v.platforms||[]),p.value]}))}/><span>{p.label}</span>{connected?<small>Ansluten</small>:null}</label>})}</div></div>
              <div className="sp102-sub"><div className="sp102-sub-title"><div><h3>AI Innehållsstudio</h3><p>Välj vilka format som ska köras.</p></div><div className="sp102-studio-actions"><button type="button" onClick={()=>{const allowed=setup.formats.filter((f)=>!(["website_item","website_item_text_ad","animated_website_item","ai_product_video","carousel_website_item"].includes(f.id))||brand.website_product_mode_available).map((f)=>f.id);updateBrand(brand.id,(v)=>({...v,studio:{...(v.studio||{}),types:(v.studio?.types||[]).length===allowed.length?[]:allowed}}));}}>{(s.studio?.types||[]).length ? "Välj alla / rensa" : "Välj alla"}</button><label className="sp102-repeat">Kör varje format <select value={s.studio?.repeats||1} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,studio:{...(v.studio||{}),repeats:Number(e.target.value)}}))}>{[1,2,3,4,5].map((n)=><option key={n} value={n}>{n}×</option>)}</select></label></div></div><div className="sp102-format-grid">{setup.formats.filter((f)=>!(["website_item","website_item_text_ad","animated_website_item","ai_product_video","carousel_website_item"].includes(f.id))||brand.website_product_mode_available).map((f)=><button key={f.id} className={s.studio?.types?.includes(f.id)?"active":""} onClick={()=>toggleFormat(brand.id,f.id)}><span>{s.studio?.types?.includes(f.id)?<CheckCircle2 size={16}/>:<Sparkles size={16}/>}</span><strong>{f.label}</strong><small>{f.estimatedCostSek!=null?`ca ${fmtMoney(f.estimatedCostSek)}`:"kostnad mäts"}</small></button>)}</div>
                {(s.studio?.types||[]).some((id)=>["offer_campaign","giveaway","focus_source","manual_prompt"].includes(id))?<div className="sp102-special">
                  {s.studio.types.includes("offer_campaign")?<label><span>Erbjudande / kampanjkod</span><textarea value={s.studio.special?.offer||""} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,studio:{...v.studio,special:{...(v.studio?.special||{}),offer:e.target.value}}}))} placeholder="Exakt erbjudande, kod och villkor som får användas…"/></label>:null}
                  {s.studio.types.includes("giveaway")?<label><span>Tävling / giveaway</span><textarea value={s.studio.special?.giveaway||""} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,studio:{...v.studio,special:{...(v.studio?.special||{}),giveaway:e.target.value}}}))} placeholder="Pris, slutdatum och regler som ska testas…"/></label>:null}
                  {s.studio.types.includes("focus_source")?<label><span>Fokussida</span><input value={s.studio.special?.focusUrl||""} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,studio:{...v.studio,special:{...(v.studio?.special||{}),focusUrl:e.target.value}}}))} placeholder="https://…"/></label>:null}
                  {s.studio.types.includes("manual_prompt")?<label><span>Egen idé</span><textarea value={s.studio.special?.manualPrompt||""} onChange={(e)=>updateBrand(brand.id,(v)=>({...v,studio:{...v.studio,special:{...(v.studio?.special||{}),manualPrompt:e.target.value}}}))} placeholder="Skriv den egna idén som ska köras…"/></label>:null}
                </div>:null}
              </div>
              <div className="sp102-sub"><h3>Kalenderkampanjer</h3><p className="sp102-muted">Välj hela kampanjer eller enskilda kampanjinlägg. De genereras nu direkt, men behåller kampanjens riktiga tema och produktlogik.</p>{brand.campaigns?.length?<div className="sp102-campaigns">{brand.campaigns.map((c)=>{const pick=s.campaigns?.[c.id];return <div key={c.id} className={`sp102-campaign ${pick?.enabled?"active":""}`}><label className="sp102-campaign-head"><input type="checkbox" checked={!!pick?.enabled} onChange={()=>toggleCampaign(brand.id,c)}/><span><strong>{c.title}</strong><small>{c.start_date||c.event_date||"—"} – {c.end_date||c.event_date||"—"} · {c.post_plan.length} inlägg</small></span></label>{pick?.enabled?<div className="sp102-campaign-posts">{c.post_plan.map((p,i)=><label key={i}><input type="checkbox" checked={pick.postIndexes?.includes(i)||false} onChange={()=>toggleCampaignPost(brand.id,c.id,i)}/><span><strong>{i+1}. {p.role||p.purpose||"Kampanjinlägg"}</strong><small>{setup.formats.find((f)=>f.id===p.content_type_id)?.label||p.content_type_id}</small></span></label>)}</div>:null}</div>})}</div>:<div className="sp102-empty">Inga aktiva kalenderkampanjer för detta varumärke.</div>}</div>
            </div>:null}
          </article>})}</div>
        </section>
        <section className="sp102-launch"><div><span>REDO ATT KÖRA</span><h2>{summary.total} testjobb</h2><p>{selectedBrands.length} varumärken · {summary.studio} Studio-inlägg · {summary.campaign} kampanjinlägg</p><div className="sp102-launch-notes"><b>⚡ Körs så snart som möjligt</b><b>🧾 Kundkrediter: 0</b><b>💰 Uppskattad AI-kostnad: {summary.estimated?fmtMoney(summary.estimated):"mäts under körningen"}</b><b>✅ Hamnar i vanliga Godkänn</b></div></div><button disabled={starting||!summary.total} onClick={startTest}>{starting?<LoaderCircle className="admin-spin"/>:<Play/>} Starta masstest</button></section>
      </>}

      <section className="sp102-history"><div className="sp102-section-head"><div><span>2</span><div><h2>Testkörningar</h2><p>Följ kö, failures och faktisk kostnad.</p></div></div></div><div className="sp102-batches">{setup.batches?.length?setup.batches.map((b)=><button key={b.id} className={activeBatchId===b.id?"active":""} onClick={()=>setActiveBatchId(b.id)}><strong>{b.title}</strong><span>{statusLabel[b.status]||b.status} · {b.total_jobs} jobb</span><small>{fmtDate(b.created_at)}</small></button>):<div className="sp102-empty">Inga masstest ännu.</div>}</div></section>

      {batchDetail?<section className="sp102-results"><header><div><span>RESULTAT</span><h2>{batchDetail.batch.title}</h2><p>{batchDetail.counts.completed} klara · {batchDetail.counts.running} körs · {batchDetail.counts.waiting} väntar · {batchDetail.counts.failed} fel</p></div><div className="sp102-result-actions"><a href={`/admin/post-approvals?view=queue&testBatch=${batchDetail.batch.id}`}>Visa i Godkänn</a>{batchDetail.counts.failed?<><button onClick={rerunFailed}><RotateCcw size={15}/> Kör om fel</button><button onClick={downloadErrors}><ClipboardCopy size={15}/> Hämta diagnostik</button></>:null}</div></header>
        <div className="sp102-costs">{Object.keys(batchDetail.costTotals||{}).length?Object.entries(batchDetail.costTotals).map(([cur,val])=><b key={cur}>Faktisk kostnad: {cur} {Number(val).toFixed(6)}</b>):<b>Kostnad registreras när inläggen blir klara.</b>}</div>
        <div className="sp102-job-table">{batchDetail.jobs.map((j)=><div key={j.ruleId} className={`sp102-job ${j.status}`}><span className="sp102-job-status">{j.status==="completed"?<CheckCircle2/>:j.status==="failed"?<AlertTriangle/>:j.status==="running"?<LoaderCircle className="admin-spin"/>:<span className="dot"/>}</span><span><strong>{j.brand?.business_name}</strong><small>{j.campaign?`${j.campaign} · `:""}{j.contentTypeLabel||j.contentTypeId} · {j.platform}</small></span><span><strong>{statusLabel[j.status]||j.status}</strong><small>{j.post?.generationCost?.amount!=null?`${j.post.generationCost.currency||""} ${Number(j.post.generationCost.amount).toFixed(6)}`:"—"}</small></span>{j.status==="failed"?<button onClick={()=>copyDiagnostic(j.ruleId)} disabled={copying===j.ruleId}><ClipboardCopy size={15}/>{copying===j.ruleId?"Kopierar…":"Kopiera fellogg"}</button>:<span/>}</div>)}</div>
      </section>:null}
    </main>
  </AppLayout>;
}
